name: absensiwajahdoang
description: A face recognition attendance application for students and lecturers.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+5
  image: ^4.1.3
  path: ^1.8.3
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  provider: ^6.1.1
  image_picker: ^1.0.4
  qr_flutter: ^4.0.0
  barcode_scan2: ^4.5.1
  mobile_scanner: ^7.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true